trigger:
  branches:
    include:
      - master
  batch: true

variables:
  - group: 'mern-container-apps-variables'

pool:
  name: Azure Pipelines

stages:
- stage: CodeQuality
  displayName: Code Quality Analysis
  jobs:
  - job: SonarQubeAnalysis
    displayName: SonarQube Analysis
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '20.x'
    
    - task: SonarQubePrepare@5
      displayName: 'Prepare SonarQube analysis'
      inputs:
        SonarQube: '$(sonarQubeServiceConnection)'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'mern-app'
        cliProjectName: 'MERN Application testing 1'
        cliProjectVersion: '$(Build.BuildNumber)'
        cliSources: '.'
        extraProperties: |
          sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js,**/*.spec.js
          sonar.javascript.lcov.reportPaths=generated-app/coverage/lcov.info,backend/coverage/lcov.info
          sonar.typescript.lcov.reportPaths=generated-app/coverage/lcov.info
          sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/jest.config.js,**/webpack.config.js
    
    # Frontend Analysis
    - script: |
        cd generated-app
        npm install
        npm run test:coverage
      displayName: 'Frontend - Install dependencies and run tests with coverage'
      continueOnError: true

    - script: |
        cd generated-app
        npm run lint:sonar || true
      displayName: 'Frontend - Run ESLint for SonarQube'
      continueOnError: true
    
    #Backend Analysis
    - script: |
        cd backend
        npm install
        npm run test:coverage
      displayName: 'Backend - Install dependencies and run tests with coverage'
      continueOnError: true
    
    - script: |
        cd backend
        npm run lint:sonar
      displayName: 'Backend - Run ESLint for SonarQube'
      continueOnError: true
    
    - task: SonarQubeAnalyze@5
      displayName: 'Run SonarQube analysis'
    
    - task: SonarQubePublish@5
      displayName: 'Publish SonarQube results'
      inputs:
        pollingTimeoutSec: '300'

- stage: ComposeTest
  displayName: Run Docker Compose
  dependsOn: CodeQuality
  condition: succeeded()
  jobs:
  - job: ComposeRun
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0

    - script: |
        docker-compose -f docker-compose.yml build
      displayName: Build Docker Compose

    - script: |
        docker-compose -f docker-compose.yml up -d
      displayName: Run Containers

    - script: |
        sleep 20
        docker inspect --format='{{json .State.Health.Status}}' backend
      displayName: Wait for Backend Health

    - script: docker ps -a
      displayName: Show Running Containers

    - script: docker-compose down
      displayName: Cleanup Containers

- stage: Build
  displayName: Build and Push Docker Images
  dependsOn: ComposeTest
  condition: succeeded()
  jobs:
  - job: DockerBuildPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0

    - task: Docker@2
      displayName: Build and Push Frontend Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)-frontend
        dockerfile: generated-app/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
        arguments: '--build-arg MONGO_URI=$(MONGO_URI)'

    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)-backend
        dockerfile: backend/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
# - stage: Build
#   displayName: Build and Push Images
#   dependsOn: CodeQuality
#   condition: succeeded()
#   jobs:
#   - job: BuildFrontend
#     displayName: Build Frontend
#     steps:
#     - task: Docker@2
#       displayName: Build and push frontend image
#       inputs:
#         command: buildAndPush
#         repository: $(imageRepository)-frontend
#         dockerfile: frontend/Dockerfile
#         containerRegistry: $(dockerRegistryServiceConnection)
#         tags: |
#           $(tag)
#           latest

#   - job: BuildBackend
#     displayName: Build Backend
#     steps:
#     - task: Docker@2
#       displayName: Build and push backend image
#       inputs:
#         command: buildAndPush
#         repository: $(imageRepository)-backend
#         dockerfile: backend/Dockerfile
#         containerRegistry: $(dockerRegistryServiceConnection)
#         tags: |
#           $(tag)
#           latest

# - stage: Deploy
#   displayName: Deploy to Container Apps
#   dependsOn: Build
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy to Azure Container Apps
#     environment: 'production'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureResourceManagerTemplateDeployment@3
#             displayName: Deploy Container Apps
#             inputs:
#               deploymentScope: 'Resource Group'
#               azureResourceManagerConnection: 'your-azure-connection'
#               subscriptionId: 'your-subscription-id'
#               action: 'Create Or Update Resource Group'
#               resourceGroupName: '$(resourceGroupName)'
#               location: 'East US'
#               templateLocation: 'Linked artifact'
#               csmFile: 'container-apps-template.json'
#               overrideParameters: |
#                 -frontendImage $(containerRegistry)/$(imageRepository)-frontend:$(tag)
#                 -backendImage $(containerRegistry)/$(imageRepository)-backend:$(tag)
#                 -mongoConnectionString $(MONGODB_CONNECTION_STRING)
#                 -containerRegistryServer $(containerRegistry)
#                 -containerRegistryUsername $(CONTAINER_REGISTRY_USERNAME)
#                 -containerRegistryPassword $(CONTAINER_REGISTRY_PASSWORD)

#           - task: AzureCLI@2
#             displayName: 'Update Container Apps'
#             inputs:
#               azureSubscription: 'your-azure-connection'
#               scriptType: 'bash'
#               scriptLocation: 'inlineScript'
#               inlineScript: |
#                 # Update backend container app
#                 az containerapp update \
#                   --name mern-backend \
#                   --resource-group $(resourceGroupName) \
#                   --image $(containerRegistry)/$(imageRepository)-backend:$(tag)
#                 